apiVersion: v1
kind: Service
metadata:
  name: demo-python-application-service
  labels:
    app: {{ template "demo-python-app.name" . }}
    chart: {{ template "demo-python-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      name: flask
      protocol: TCP
  selector:
    app: {{ template "demo-python-app.name" . }}
    release: {{ .Release.Name }}