apiVersion: v1
kind: Service
metadata:
  name: demo-python-application-service
spec:
  type: ClusterIP
  ports:
    - targetPort: 9090
      name: flask
      port: 9090
      protocol: TCP
  selector:
    app: demo-python-application