name: Create and publish a Docker image

on:
  pull_request:
    types:
      - closed
    branches:
      - 'feature/**'

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ vars.REGISTRY_NAME }}

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged

  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ vars.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Update Image Version in the related HelmChart values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'demo-python-app/values.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.sha }}
          branch: deployment/${{ steps.image.outputs.version }}
          targetBranch: main
          createPR: true
          message: 'Update Image Version to ${{ github.sha }}'